alias ls='ls --color=auto'
alias grep='grep --color=auto'

alias redis-server='redis-server /usr/local/etc/redis.conf'

alias cdin='cd ~/workspace/inori/'
alias cdsa='cd ~/workspace/sakura/'

# Eleme aliases.
# --------------
alias sshed='ssh -t elemedev@192.168.108.120'

# Walle.
alias cdw='cd ~/workspace/eleme/walle/'
alias cdwlm='cd ~/workspace/eleme/walle/lib/model/'
alias cdwlz='cd ~/workspace/eleme/walle/lib/Zeus/'
alias cdwm='cd ~/workspace/eleme/walle/apps/walle/modules/'
alias cdwjs='cd ~/workspace/eleme/walle/web/walle/js/walle/'

# Zeus2.
alias cdz='cd ~/workspace/eleme/zeus2/'
alias cdza='cd ~/workspace/eleme/zeus2/zeus/eas/'
alias cdzo='cd ~/workspace/eleme/zeus2/zeus/eos/'
alias cdzr='cd ~/workspace/eleme/zeus2/zeus/ers/'
alias cdzu='cd ~/workspace/eleme/zeus2/zeus/eus/'

alias pkz='sh ~/bats/stop_zeus'

alias zas='zeus_oas_server'
alias zos='zeus_eos_server'
alias zrs='zeus_ers_server'
alias zus='zeus_eus_server'

alias zah='zeus_oas_helper'
alias zoh='zeus_eos_helper'
alias zrh='zeus_ers_helper'
alias zuh='zeus_eus_helper'

# Earthshaker.
alias cde='cd ~/workspace/eleme/earthshaker/'
alias cdee='cd ~/workspace/eleme/earthshaker/earthshaker/'
alias cdeev='cd ~/workspace/eleme/earthshaker/earthshaker/views/'
alias cdeth='cd ~/workspace/eleme/earthshaker/test/http/'
# -------------
