alias tmux='tmux -2'

alias la='ls -a'
alias ll='ls -la'

alias redis-server='redis-server /usr/local/etc/redis.conf'

alias pweb='python -m SimpleHTTPServer'

alias goagent='sudo python /Applications/goagent/local/proxy.py'

alias cdin='cd ~/workspace/inori/'
alias cdko='cd ~/workspace/kotoba/'
alias cdsa='cd ~/workspace/sakura/'


alias cdinm='cd ~/workspace/inori/inori/models/'
alias cdinv='cd ~/workspace/inori/inori/views/'
alias cdint='cd ~/workspace/inori/inori/templates/'

# Eleme aliases.
# --------------
alias sshed='ssh elemedev'
alias sshin='ssh inori'

# Walle.
alias cdw='cd ~/workspace/eleme/walle/'
alias cdwlm='cd ~/workspace/eleme/walle/lib/model/'
alias cdwlz='cd ~/workspace/eleme/walle/lib/Zeus/'
alias cdwm='cd ~/workspace/eleme/walle/apps/walle/modules/'
alias cdwjs='cd ~/workspace/eleme/walle/web/walle/js/walle/'

# Mintaka.
alias cdm='cd ~/workspace/eleme/mintaka/'

# Paladin.
alias cdp='cd ~/workspace/eleme/paladin/'
alias cdpt='cd ~/workspace/eleme/paladin/paladin/templates'
alias cdpm='cd ~/workspace/eleme/paladin/paladin/models'
alias cdpv='cd ~/workspace/eleme/paladin/paladin/views'
alias cdpu='cd ~/workspace/eleme/paladin/paladin/utils'
alias cdps='cd ~/workspace/eleme/paladin/paladin/static'

# Coffee.
alias cdc='cd ~/workspace/eleme/coffee/'
alias cdch='cd ~/workspace/eleme/coffee/coffee/hr/'
alias cdcw='cd ~/workspace/eleme/coffee/coffee/wf/'
alias cdca='cd ~/workspace/eleme/coffee/coffee/webapi/'

# Zeus2.
alias cdz='cd ~/workspace/eleme/zeus2/'
alias cdza='cd ~/workspace/eleme/zeus2/zeus/oas/'
alias cdzo='cd ~/workspace/eleme/zeus2/zeus/eos/'
alias cdzr='cd ~/workspace/eleme/zeus2/zeus/ers/'
alias cdzs='cd ~/workspace/eleme/zeus2/zeus/sms/'
alias cdzu='cd ~/workspace/eleme/zeus2/zeus/eus/'

alias cdzt='cd ~/workspace/eleme/zeus2/tests/'
alias cdzat='cd ~/workspace/eleme/zeus2/tests/functional/oas/'
alias cdzot='cd ~/workspace/eleme/zeus2/tests/functional/eos/'
alias cdzrt='cd ~/workspace/eleme/zeus2/tests/functional/ers/'
alias cdzst='cd ~/workspace/eleme/zeus2/tests/functional/sms/'
alias cdzut='cd ~/workspace/eleme/zeus2/tests/functional/eus/'

alias pkz='pkill -9 zhelper'

alias zah='zhelper oas'
alias zoh='zhelper eos'
alias zrh='zhelper ers'
alias zsh='zhelper sms'
alias zuh='zhelper eus'

# Earthshaker.
alias cde='cd ~/workspace/eleme/earthshaker/'
alias cdee='cd ~/workspace/eleme/earthshaker/earthshaker/'
alias cdeev='cd ~/workspace/eleme/earthshaker/earthshaker/views/'
alias cdet='cd ~/workspace/eleme/earthshaker/test/'
alias cdeth='cd ~/workspace/eleme/earthshaker/test/http/'
# -------------

# Openapi.
alias cdo='cd ~/workspace/eleme/prophet/'
alias cdoo='cd ~/workspace/eleme/prophet/prophet/'
alias cdoov='cd ~/workspace/eleme/prophet/prophet/views/'
alias cdot='cd ~/workspace/eleme/prophet/test/'
alias cdoth='cd ~/workspace/eleme/prophet/test/http/'

# Priest
alias cdr='cd ~/workspace/eleme/priest/'
alias cdrr='cd ~/workspace/eleme/priest/priest/'
alias cdrrv='cd ~/workspace/eleme/priest/priest/views/'
alias cdrrm='cd ~/workspace/eleme/priest/priest/models/'

alias scpm='scp p-service-2:~/export_active_user.xls /Users/stdrickforce/Documents/'
