alias tmux='tmux -2'

alias rb='source ~/.bashrc'

alias la='ls -a'
alias ll='ls -la'

alias visupervisor='vi /usr/local/etc/supervisord.conf'
alias vinginx='vi /usr/local/etc/nginx/'

alias cdin='cd ~/workspace/inori/'
alias cdsa='cd ~/workspace/sakura/'

alias cdinm='cd ~/workspace/inori/inori/models/'
alias cdinv='cd ~/workspace/inori/inori/views/'
alias cdint='cd ~/workspace/inori/inori/templates/'

# XHS.
alias cdx='cd ~/workspace/xhs'
alias cdxs='cd ~/workspace/xhs/front_main2/service/'
alias cdxm='cd ~/workspace/xhs/front_main2/model/'
alias cdxf='cd ~/workspace/xhs/front_main2/front/'
alias cdxa='cd ~/workspace/xhs/front_main2/front/api/'


# Leoric.
alias svl='source /srv/virtualenvs/leoricenv/bin/activate'
alias cdl='cd ~/workspace/leoric/'
alias cdld='cd ~/workspace/leoric/document/'
alias cdlm='cd ~/workspace/leoric/leoric/models/'
alias cdls='cd ~/workspace/leoric/leoric/services/'
alias cdla='cd ~/workspace/leoric/leoric/apps/'

# Azeroth.
alias sva='source /srv/virtualenvs/azerothenv/bin/activate'
alias cda='cd ~/workspace/azeroth'

# Draenor.
alias svd='source /srv/virtualenvs/draenorenv/bin/activate'
alias cdd='cd ~/workspace/eleme/draenor/'
alias cddc='cd ~/workspace/eleme/draenor/draenor/core/'
alias cddr='cd ~/workspace/eleme/draenor/draenor/rpc/'
alias cddu='cd ~/workspace/eleme/draenor/draenor/dus/'
alias cdds='cd ~/workspace/eleme/draenor/draenor/dss/'
alias cddo='cd ~/workspace/eleme/draenor/draenor/dos/'
alias cddd='cd ~/workspace/eleme/draenor/draenor/dds/'
alias cddh='cd ~/workspace/eleme/draenor/draenor/hrs/'

# Paladin.
alias svp='source /srv/virtualenvs/paladinenv/bin/activate'
alias cdp='cd ~/workspace/eleme/paladin/'
alias cdpa='cd ~/workspace/eleme/paladin/paladin/apps'
alias cdpd='cd ~/workspace/eleme/paladin/paladin/dal'
alias cdpm='cd ~/workspace/eleme/paladin/paladin/models'
alias cdpu='cd ~/workspace/eleme/paladin/paladin/utils'
alias cdps='cd ~/workspace/eleme/paladin/paladin/static'

# Turalyon.
alias cdt='cd ~/workspace/eleme/turalyon/'

# Zeus2.
alias svz='source /srv/virtualenvs/zeusenv/bin/activate'
alias cdz='cd ~/workspace/eleme/zeus2/'
alias cdzc='cd ~/workspace/eleme/zeus_core/zeus_core/'
alias cdzo='cd ~/workspace/eleme/zeus2/zeus/eos/'
alias cdzr='cd ~/workspace/eleme/zeus2/zeus/ers/'
alias cdzu='cd ~/workspace/eleme/zeus2/zeus/eus/'
